apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - app: writer
                  namespace: default
                - app: enqueuer
                  namespace: default
                - app: memorizer
                  namespace: default
                - app: ascii-frontend
                  namespace: default
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: In
                    values: [dev, prod]
  template:
    metadata:
      name: "{{.app}}-{{.name}}"
      labels:
        app: "{{.app}}"
        env: "{{.name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/fullstack-pw/demo-apps
        targetRevision: HEAD
        path: "apps/{{.app}}/kustomize/overlays/{{.name}}"
      destination:
        server: "{{.server}}"
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
